spring.application.name=demo
server.port=9001
server.forward-headers-strategy=framework 

spring.datasource.url=jdbc:mysql://localhost:3306/IT_Policy_Violation_Detection_API?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Amypo
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

//# JWT Settings (REQUIRED for your JwtUtil)
//jwt.secret=9a67471b7f12e06c58908f9c09c952b1b5e39626e27302f37c4d5b248a3d5f6e
//jwt.validity=3600000
//jwt.test-mode=true